mongo:
  secretName: PLUANG_IDSS_MONGO_CONFIG
  appName: pricing-mongo-prod-jkt
kafka:
  consumer:
    topic:
      idssOhlc: idss-candle-v2
    groupId: trading-ai-bot-consumer-production
  producer:
    topic:
      tradingIdssAiMessages: trading-idss-ai-messages
      tradingIdssPortfolioState: trading-idss-portfolio-state
      tradingIdssPortfolioStateHistory: trading-idss-portfolio-state-history
      tradingIdssTradeHistory: trading-idss-trade-history
      tradingIdssAiDecisions: trading-idss-ai-decisions
  secretName: KAFKA_CONFIG_NODE
tradingBotSecretName: PLUANG_TRADING_AI_BOT
projectS3Path: s3://trading-ai-multi-assets/
awsSecretName: AWS_KEY_QUANT_TEAM_S3_ACCESS
awsRegionName: ap-southeast-3
filePathAwsKey: AWS_key.json
slackAlert:
  channel: quant-alert-production
  infoChannel: quant-alert-dev
  attentionEmailList:
    - sungjin.oh@pluang.com
    - to.vanhung@pluang.com
    - rui.zhao@pluang.com
